# Copyright 2019 Gary Yu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: trusty
sudo: required
language: rust
rust:
- stable
git:
  depth: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libssl-dev
    - cmake
    - gcc
    - binutils-dev

cache:
  cargo: true
  timeout: 240
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/rust/target"

env:
  global:
  - RUST_BACKTRACE="1"
  - RUSTFLAGS="-C debug-assertions"

matrix:
  include:
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="aarch64"
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="x86_64"
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="armv7s"
  - os: osx
    env: CI_JOB="release"     CI_JOB_ARGS="aarch64"
  - os: osx
    env: CI_JOB="release"     CI_JOB_ARGS="x86_64"
  - os: osx
    env: CI_JOB="release"     CI_JOB_ARGS="armv7s"

before_script:
- rustup target add aarch64-apple-ios x86_64-apple-ios armv7s-apple-ios
- cargo install cargo-lipo || true

script:
- bash .ci/general-jobs

before_cache:
- rm -f cocoa_grinwallet/Library/*

before_deploy:
- bash .ci/release-jobs

deploy:
  provider: releases
  api_key:
    secure: IU0W1oSWS+tFVDlldXwIJCDR2UQr6+3StpMV1hlhECQC3e8kUbY7xSsNu27y0Qln3i8mz1q1RoJvP8ZWfCo7boMA7m3LFWg7/BKNS1riRXgymqMElcQNv0FeXjRmRtCFCa2Aw6iDdueRwitkhny3MS7Wws9MZ8N1k/hapQbKx6DEEZIHhRzIDb+uaWvx6ojyinD5CSdPfU0/gTPz0OH0OcJZBY7Qa/P1DGMWi/NO6E56ZNetOPDXdBfwaJ30io2DS3b5duzLLS4LjjxfEMKDjyirbaRmKV2NLJmFOi2wvw6bX+oklI8TrdJSqWcDwSJMrfrg4+f+cTMvc60DJJqmDlX5fWKErMePFzu1r5aTkXVpwfQwMSKtuqZjYRsgYlXlVnAnzU2KwhO8TAjM1XV2CFgrijZ5bmB12vn6EewHgEVtIPxCBRFqZ2MkRKiOkNNi7wHN5vViKweFEa+/gj+YsJ5gsJYfJJk7yeRQ0YUkSw3y3WTIsmeR3x/hHtNJaC4KyhYdXn+MIFCYSktoUMCfHXtm7EGxwssKcxqMKP+Rkz3gajICav9ReKGXlQHO2EZo409mGLZnkj6v1yQ+SFFMLIKTqyXsGe+A3rCBJkD40FKHTvPKLSA2OIE70nga55K8KD/AgklWcqvPMoPAC16qab0Olw+kJ4fSPguDZhHatKE=
  file_glob: true
  file: cocoa_grinwallet/Library/libgrinwallet*.*
  skip_cleanup: true
  on:
    repo: gottstech/cocoa_grinwallet
    tags: true
